@host = http://localhost:{{$dotenv PORT}}/
###
POST {{host}}
Content-Type: application/json

{
  "token": "{{$dotenv SLACK_TOKEN}}",
  "text": "ceiling",
  "channel_name" : "payroll",
  "user_name" : "ryancwynar"
}